FROM node:20-alpine

WORKDIR /app

# Copy package files first
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app
COPY . .

EXPOSE 5173

ENV CHOKIDAR_USEPOLLING=true

# Vite dev server
CMD ["npm", "run", "dev"]